/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign6;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventSubtype { 
  CONTACT_FORM, CONTACT_BANNER, CONTACT_BUTTON, DEALER_PHONE, FEATURES, GET_DIRECTIONS, VEHICLE_HISTORY, ALTERNATIVE, BADGES, BADGE_DETAIL, PHOTO_MODAL, MARKET_REPORT, NULL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventSubtype\",\"namespace\":\"com.refactorlabs.cs378.assign6\",\"symbols\":[\"CONTACT_FORM\",\"CONTACT_BANNER\",\"CONTACT_BUTTON\",\"DEALER_PHONE\",\"FEATURES\",\"GET_DIRECTIONS\",\"VEHICLE_HISTORY\",\"ALTERNATIVE\",\"BADGES\",\"BADGE_DETAIL\",\"PHOTO_MODAL\",\"MARKET_REPORT\",\"NULL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
